# -*- coding: utf-8 -*-
# hirigana spesh

def load_full():
    hiragana = {
                "a":    "あ",
                "i":    "い",
                "u":    "う",
                "e":    "え",
                "o":    "お",
                "ka":   "か",
                "ki":   "き",
                "ku":   "く",
                "ke":   "け",
                "ko":   "こ",
                "kya":  "きゃ",
                "kyu":  "きゅ",
                "kyo":  "きょ",
                "sa":   "さ",
                "shi":  "し",
                "su":   "す",
                "se":   "せ",
                "so":   "そ",
                "sha":  "しゃ",
                "shu":  "しゅ",
                "sho":  "しょ",
                "ta":   "た",
                "chi":  "ち",
                "tsu":  "つ",
                "te":   "と",
                "to":   "と",
                "cha":  "ちゃ",
                "chu":  "ちゅ",
                "cho":  "ちょ",
                "na":   "な",
                "ni":   "に",
                "nu":   "ぬ",
                "ne":   "ね",
                "no":   "の",
                "nya":  "にゃ",
                "nyu":  "にゅ",
                "nyo":  "にょ",
                "ha":   "は",
                "hi":   "ひ",
                "fu":   "ふ",
                "he":   "へ",
                "ho":   "ほ",
                "hya":  "ひゃ",
                "hyu":  "ひゅ",
                "hyo":  "ひょ",
                "ma":   "ま",
                "mi":   "み",
                "mu":   "む",
                "me":   "め",
                "mo":   "も",
                "mya":  "みゃ",
                "myu":  "みゅ",
                "myo":  "みょ",
                "ya":   "や",
                "yu":   "ゆ",
                "yo":   "よ",
                "ra":   "ら",
                "ri":   "り",
                "ru":   "る",
                "re":   "れ",
                "ro":   "ろ",
                "rya":  "りゃ",
                "ryu":  "りゅ",
                "ryo":  "りょ",
                "wa":   "わ",
                "wi":   "ゐ",
                "we":   "ゑ",
                "wo":   "を",
                "n":    "ん",
                "ga":   "が",
                "gi":   "ぎ",
                "gu":   "ぐ",
                "ge":   "げ",
                "go":   "ご",
                "gya":  "ぎゃ",
                "gyu":  "ぎゅ",
                "gyo":  "ぎょ",
                "za":   "ざ",
                "ji":   "じ",
                "zu":   "ず",
                "ze":   "ぜ",
                "zo":   "ぞ",
                "ja":   "じゃ",
                "ju":   "じゅ",
                "jo":   "じょ",
                "da":   "だ",
                "ji":   "ぢ",
                "dzu":  "づ",
                "de":   "で",
                "do":   "ど",
                "ja":   "ぢゃ",
                "ju":   "ぢゅ",
                "jo":   "ぢょ",
                "ba":   "ば",
                "bi":   "び",
                "bu":   "ぶ",
                "be":   "べ",
                "bo":   "ぼ",
                "bya":  "びゃ",
                "byu":  "びゅ",
                "byo":  "びょ",
                "pa":   "ぱ",
                "pi":   "ぴ",
                "pu":   "ぷ",
                "pe":   "ぺ",
                "po":   "ぽ",
                "pya":  "ぴゃ",
                "pyu":  "ぴゅ",
                "pyo":  "ぴょ",
                "vu":   "ゔ"
                }
    return hiragana

def load_romanji():
    romanji =                 ["a",   
                "i",   
                "u",   
                "e",   
                "o",   
                "ka",  
                "ki",  
                "ku",  
                "ke",  
                "ko",  
                "kya", 
                "kyu", 
                "kyo", 
                "sa",  
                "shi", 
                "su",  
                "se",  
                "so",  
                "sha", 
                "shu", 
                "sho", 
                "ta",  
                "chi", 
                "tsu", 
                "te",  
                "to",  
                "cha", 
                "chu", 
                "cho", 
                "na",  
                "ni",  
                "nu",  
                "ne",  
                "no",  
                "nya", 
                "nyu", 
                "nyo", 
                "ha",  
                "hi",  
                "fu",  
                "he",  
                "ho",  
                "hya", 
                "hyu", 
                "hyo", 
                "ma",  
                "mi",  
                "mu",  
                "me",  
                "mo",  
                "mya", 
                "myu", 
                "myo", 
                "ya",  
                "yu",  
                "yo",  
                "ra",  
                "ri",  
                "ru",  
                "re",  
                "ro",  
                "rya", 
                "ryu", 
                "ryo", 
                "wa",  
                "wi",  
                "we",  
                "wo",  
                "n",   
                "ga",  
                "gi",  
                "gu",  
                "ge",  
                "go",  
                "gya", 
                "gyu", 
                "gyo", 
                "za",  
                "ji",  
                "zu",  
                "ze",  
                "zo",  
                "ja",  
                "ju",  
                "jo",  
                "da",  
                "ji",  
                "dzu", 
                "de",  
                "do",  
                "ja",  
                "ju",  
                "jo",  
                "ba",  
                "bi",  
                "bu",  
                "be",  
                "bo",  
                "bya", 
                "byu", 
                "byo", 
                "pa",  
                "pi",  
                "pu",  
                "pe",  
                "po",  
                "pya", 
                "pyu", 
                "pyo", 
                "vu"]
    return romanji
    

if __name__ == "__main__":
    pass
